LEARNING_RATE: 0.001
OPTIMIZER: adam
ACTIVATION: softmax
FREEZE_TILL: null     # or set an integer like 4
IMAGE_SIZE: [224, 224, 3]
INCLUDE_TOP: False
WEIGHTS: imagenet
CLASSES: 2
EPOCHS: 1
BATCH_SIZE: 16
AUGMENTATION: True
